### ISSUE TITLE
RootTokenContract.cpp, uninitialized wallet code condition may produce excessive coins loss

### ISSUE THREAD

**Issue by unboxedtype** [tonlabs/flex#29]
After the constructor call, the `RootTokenContract` to be fully initialized, the method `setWalletCode` has to be called.
This method sets the code for `TONTokenWallet` contracts being deployed on request.

The function `calc_wallet_init` relies on the `wallet_code_.get()` value, and uses it without any prior checks. 
In case the `wallet_code_` field is not initialized, the call will throw exception. This is nothing special, but in the `deployWallet()` case, it may happen after the tvm.accept() call. In this case, excessive coins loss may happen due to charging by all network validators.

https://github.com/tonlabs/flex/blob/6d4279d94dfa91b0e2c8670a78282e223fef2025/tokens-fungible/RootTokenContract.cpp#L91

It is proposed to add `require(hasWalletCode(), error_code::wallet_code_not_initialized)` checks into both `deployWallet` and `deployEmptyWallet` methods.

**Comment by azhogin** [comment]
Fixed, also added tvm_commit() call in `check_external_owner`.
